name: ðŸ”´ BUG æŠ¥å‘Š
description: ç¨‹åºæŠ¥é”™æˆ–å‡ºçŽ°æ„æ–™ä¹‹å¤–çš„æƒ…å†µ
type: "Bug"
body:
  - type: textarea
    id: description
    attributes:
      label: BUGæè¿°
      description: å‘ç”Ÿäº†ä»€ä¹ˆBUG
      placeholder: |
        ç‚¹å‡»æœ€å°åŒ–æŒ‰é’®ç¨‹åºä¼šå´©æºƒ
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: å¤çŽ°æ­¥éª¤
      description: æ˜¯å¦‚ä½•å‡ºçŽ°æ­¤ bug çš„
      placeholder: |
        1. æ‰“å¼€ç¨‹åº
        2. ç‚¹å‡»æœ€å°åŒ–æŒ‰é’®
        3. ç¨‹åºå´©æºƒ
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: é”™è¯¯ä¿¡æ¯(å¦‚æžœæœ‰çš„è¯)
      description: å¦‚æžœä½ æ˜¯é€šè¿‡é”™è¯¯å¼¹çª—åˆ°è¿™é‡Œçš„è¯ï¼Œç›´æŽ¥æŠŠå¤åˆ¶çš„é”™è¯¯ä¿¡æ¯ç²˜è´´åˆ°è¿™é‡Œæ¥å³å¯ã€‚
      placeholder: |
        é”™è¯¯ä¿¡æ¯çœ‹èµ·æ¥æ˜¯è¿™æ ·çš„:

        =====[PvzLauncher é”™è¯¯ä¿¡æ¯]=====

        System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
        ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
        at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
        at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
        at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
        --- End of inner exception stack trace ---
        at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
        at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        at System.Net.Http.HttpConnectionPool.InjectNewHttp11ConnectionAsync(QueueItem queueItem)
        at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
        at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        at System.Net.Http.SocketsHttpHandler.<SendAsync>g__CreateHandlerAndSendAsync|115_0(HttpRequestMessage request, CancellationToken cancellationToken)
        at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
        at PvzLauncherRemake.Pages.PageDownload.Initialize()

        =========================
    validations:
      required: false
