name: 🟡 为游戏库贡献
description: 你可以将你知道的植物大战僵尸版本贡献到游戏库，让玩家可以直接从启动器下载页面下载到你贡献的游戏！
type: "游戏库"
body:
  - type: input
    id: gamename
    attributes:
      label: 游戏名称
      description: 植物大战僵尸游戏名称或改版名称
      placeholder: |
        例如: 植物大战僵尸β版
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: 来源
      description: 提供原作者的改版宣传帖或者个人空间等一切可以下载该改版的地方
      placeholder: |
        例如: https://space.bilibili.com/xxxxxxx
    validations:
      required: true

